### ISSUE TITLE
Test app banned - Cobalt 0.0.5

### ISSUE THREAD

**Issue by nfrfab** [Auties00/Cobalt#482] opened 2024-04-18 22:43 UTC
The test app was working for two days until WhatsApp banned it

WhatsApp still works on my cell phone, I guess WhatsApp only banned the session of the test app

code:

private static void ultimaConexionWeb() {
        api = Whatsapp.webBuilder() // Use the Web api
                .lastConnection() // Deserialize the last connection, or create a new one if it doesn't exist
                .unregistered(QrHandler.toTerminal()) // Print the QR to the terminal
                .addLoggedInListener(api -> System.out.printf("Connected: %s%n", api.store().privacySettings())) // Print a message when connected
                .addDisconnectedListener(reason -> System.out.printf("Disconnected: %s%n", reason)) // Print a message when disconnected
                .addNewChatMessageListener(App::onMessage)
                .addSocketEventListener(App::onSocketEvent)
                .connect() // Connect to Whatsapp asynchronously
                .join(); // Await the result
    }

private static void onMessage(Whatsapp api, MessageInfo info) {
        try {
            String jsonMensaje = info.toJson();
            System.out.println(jsonMensaje);
            System.out.println("=============");
	    ...
        } catch (Exception ex) {
            System.out.println("Error onMessage: "+ ex.getLocalizedMessage());
        }

    }

private static void onSocketEvent(Whatsapp api, SocketEvent event) {
        String evento = event.toString();
        if (!evento.equalsIgnoreCase("PING")) {
            System.out.println("onSocketEvent: " + event.toString() + " " + new Date().toString());
        }
    }

**Comment by nfrfab** [comment] 2024-04-18 22:45
Summary:

onSocketEvent: OPEN Sun Apr 14 21:55:15 ART 2024
...
onSocketEvent: OPEN Sun Apr 14 22:45:17 ART 2024
Connected: [PrivacySettingEntry[type=READ_RECEIPTS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=STATUS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=PROFILE_PIC, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ONLINE, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=CALL_ADD, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=LAST_SEEN, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ADD_ME_TO_GROUPS, value=EVERYONE, excluded=[]]]
Disconnected: RECONNECTING
onSocketEvent: OPEN Sun Apr 14 23:35:17 ART 2024
Connected: [PrivacySettingEntry[type=READ_RECEIPTS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=STATUS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=PROFILE_PIC, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ONLINE, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=CALL_ADD, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=LAST_SEEN, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ADD_ME_TO_GROUPS, value=EVERYONE, excluded=[]]]
Disconnected: RECONNECTING
onSocketEvent: OPEN Mon Apr 15 00:25:18 ART 2024
Connected: [PrivacySettingEntry[type=READ_RECEIPTS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=STATUS, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=PROFILE_PIC, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ONLINE, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=CALL_ADD, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=LAST_SEEN, value=EVERYONE, excluded=[]], PrivacySettingEntry[type=ADD_ME_TO_GROUPS, value=EVERYONE, excluded=[]]]
abr 15, 2024 12:25:23 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Detected possible network anomaly: reconnecting
onSocketEvent: OPEN Mon Apr 15 00:25:23 ART 2024
Disconnected: RECONNECTING
onSocketEvent: CLOSE Mon Apr 15 00:25:23 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:26:07 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:26:50 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:27:33 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:28:16 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:29:00 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:29:43 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:30:26 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:31:09 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:31:53 ART 2024
...
onSocketEvent: OPEN Mon Apr 15 00:33:10 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:33:53 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:34:36 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:35:20 ART 2024
onSocketEvent: OPEN Mon Apr 15 00:36:03 ART 2024
...
onSocketEvent: OPEN Tue Apr 16 18:30:42 ART 2024
onSocketEvent: OPEN Tue Apr 16 18:31:41 ART 2024
onSocketEvent: OPEN Tue Apr 16 18:32:39 ART 2024
onSocketEvent: OPEN Tue Apr 16 18:34:16 ART 2024
onSocketEvent: OPEN Tue Apr 16 18:35:14 ART 2024
Disconnected: BANNED
onSocketEvent: CLOSE Tue Apr 16 18:36:30 ART 2024

**Comment by nfrfab** [comment] 2024-04-18 22:46
While the app was running, several exceptions of the same type occurred


abr 14, 2024 9:55:17 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MESSAGE
java.lang.RuntimeException: Cannot decode message(id: 924545D368805269BC9A3941BF0-----, from: XXXXXXXXXX-XXXXXXXXXX0@g.us): message_decryption
	at it.auties.whatsapp.socket.MessageHandler.decodeChatMessage(MessageHandler.java:966)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$54(MessageHandler.java:722)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:722)
	at it.auties.whatsapp.socket.SocketHandler.decodeMessage(SocketHandler.java:447)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:107)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:201)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.notifyMessage(SocketSession.java:150)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:139)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processBinary(WebSocketImpl.java:618)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:447)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:282)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:251)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.tryChangeState(WebSocketImpl.java:861)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onBinary(WebSocketImpl.java:802)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.payloadData(MessageDecoder.java:223)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:473)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:675)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:772)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:451)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:269)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.lang.Thread.run(Thread.java:1583)
abr 14, 2024 9:55:17 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure

abr 15, 2024 12:32:11 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MESSAGE
java.lang.RuntimeException: Cannot decode message(id: 9BBD2A989F75BE2E4384F80B8E8-----, from: XXXXXXXXXX-ZZZZZZZZ0@g.us): message_decryption
	at it.auties.whatsapp.socket.MessageHandler.decodeChatMessage(MessageHandler.java:966)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$54(MessageHandler.java:722)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:722)
	at it.auties.whatsapp.socket.SocketHandler.decodeMessage(SocketHandler.java:447)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:107)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:201)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.notifyMessage(SocketSession.java:150)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:139)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processBinary(WebSocketImpl.java:618)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:447)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:282)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:251)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.tryChangeState(WebSocketImpl.java:861)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onBinary(WebSocketImpl.java:802)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.payloadData(MessageDecoder.java:223)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:473)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:675)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:772)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:451)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:269)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.lang.Thread.run(Thread.java:1583)
abr 15, 2024 12:32:11 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure
abr 15, 2024 12:32:11 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
SEVERE: Socket failure at MESSAGE
java.lang.RuntimeException: Cannot decode message(id: 9BBD2A989F75BE2E4384F80B8E8-----, from: XXXXXXXXXX-ZZZZZZZZZZ@g.us): Cannot decode message with any session
	at it.auties.whatsapp.socket.MessageHandler.decodeChatMessage(MessageHandler.java:966)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$54(MessageHandler.java:722)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:722)
	at it.auties.whatsapp.socket.SocketHandler.decodeMessage(SocketHandler.java:447)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:107)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:201)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.notifyMessage(SocketSession.java:150)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:139)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processBinary(WebSocketImpl.java:618)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:447)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:282)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:251)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.tryChangeState(WebSocketImpl.java:861)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onBinary(WebSocketImpl.java:802)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.payloadData(MessageDecoder.java:223)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:473)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:675)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:772)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:451)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:269)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.lang.Thread.run(Thread.java:1583)
abr 15, 2024 12:32:11 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$3
WARNING: Ignored failure

**Comment by nfrfab** [comment] 2024-04-18 22:47
The last day, several messages that I sent from a Whatsapp Web session in Chrome did not synchronize with my cell phone.

**Comment by lindak99** [comment] 2024-05-18 12:50
I have the same problem with version 0.0.5. I sent a message once and then after 11 hours I see "Disconnected: BANNED" in the log. In version 0.0.4. the application stopped working (no BANNED message), but it was enough to restart.

**Comment by Auties00** [comment] 2024-05-18 12:51
This will be fixed in 0.0.6

**Closed** 2024-08-24 14:31 UTC
Labels: bug

**Comment by zho** [comment] 2024-09-27 01:32
the issue is back on 0.0.7
